# Generated by Django 4.1.5 on 2023-07-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Haiku',
            fields=[
                ('haiku_id', models.AutoField(primary_key=True, serialize=False)),
                ('line_one', models.CharField(max_length=100)),
                ('line_two', models.CharField(max_length=100)),
                ('line_three', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
