# Generated by Django 4.1.5 on 2023-07-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyHaiku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=1024)),
                ('image_file', models.ImageField(upload_to='static/dailyHaiku/dalle')),
                ('date_created', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
