# Generated by Django 4.1.5 on 2023-07-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyHaiku', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_path',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_file',
        ),
    ]
