# Generated by Django 4.1.5 on 2023-07-22 10:52

import dailyHaiku.apps
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyHaiku', '0003_rename_image_path_image_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=models.ImageField(default='default', storage=dailyHaiku.apps.OverwriteStorage(), upload_to='static/dailyHaiku/dalle/Background.png'),
            preserve_default=False,
        ),
    ]
