# Generated by Django 4.1.5 on 2023-07-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyHaiku', '0004_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(default='static/dailyHaiku/dalle/none-image.png', upload_to='static/dailyHaiku/dalle/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(),
        ),
    ]
