# Generated by Django 4.1.5 on 2023-07-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyHaiku', '0005_alter_image_image_file_alter_image_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(default='static/dailyHaiku/dalle/none-image.png', max_length=1000, upload_to='static/dailyHaiku/dalle/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
    ]
