# Generated by Django 4.1.5 on 2023-07-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyHaiku', '0007_rename_image_dalleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dalleimage',
            name='image',
            field=models.ImageField(default='static/dailyHaiku/dalle/none-image.png', max_length=1000, upload_to='static/dailyHaiku/dalle/'),
        ),
    ]
