# Generated by Django 4.1.5 on 2023-07-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyHaiku', '0009_dalleimage_dalle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dalleimage',
            name='dalle_image',
        ),
        migrations.RemoveField(
            model_name='dalleimage',
            name='image',
        ),
    ]
