# Generated by Django 4.1.5 on 2023-07-22 14:30

import dailyHaiku.apps
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyHaiku', '0010_remove_dalleimage_dalle_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dalleimage',
            name='image_file',
            field=models.ImageField(default='static/dailyHaiku/dalle/none-image.png', max_length=1000, storage=dailyHaiku.apps.OverwriteStorage(), upload_to='static/dailyHaiku/dalle/'),
        ),
    ]
