# Generated by Django 4.1.5 on 2023-07-22 18:05

import dailyHaiku.apps
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyHaiku', '0011_alter_dalleimage_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dalleimage',
            name='image_file',
            field=models.ImageField(default='background/none-image.png', max_length=1000, storage=dailyHaiku.apps.OverwriteStorage(), upload_to='background/'),
        ),
    ]
